### ISSUE TITLE
Phone Number Verification on the Admin Side

### ISSUE THREAD

**Issue by hashweather** [firebase/firebase-admin-go#382] opened 2020-06-14 23:41 UTC
I have a simple use case,

I want to provide an `endpoint `to my clients `/users/register` where they capture the **phone number** and send it to the `endpoint`.

I then initiate a` Phone Number Validation Process` on the `Admin End` and send back a response to the client to enter the `verification code`  sent to them via  `/users/validate`. When they've received the verification code, they will now send it back  through another endpoint `/users/verify_code`. Upon confirmation I can now go ahead and create  a `CustomToken `and finally send back the custom token to the client for final signIn.

Is there a way to achieve this on the Go Admin Sdk?

Thanks.

**Comment by hiranya911** [comment] 2020-06-15 19:11
Duplicate of https://stackoverflow.com/questions/62380896/firebase-phone-number-verification-on-golang-admin-sdk

**Closed by hiranya911** 2020-06-15 19:11 UTC
