### ISSUE TITLE
Error when trying to install firebase-admin-go

### ISSUE THREAD

**Issue by DaanvandeHaar** [firebase/firebase-admin-go#510] opened 2022-09-13 13:10 UTC
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS Catalina 10.15.7 
  * Firebase SDK version: Latest
  * Library version: Latest
  * Firebase Product: _____ 

### [REQUIRED] Step 3: Describe the problem

When trying to install firebase-admin-go i'm getting this error:
```
go get firebase.google.com/go
# cloud.google.com/go/storage
../../go/pkg/mod/cloud.google.com/go/storage@v1.22.1/bucket.go:1504:5: cannot use r.Condition.AgeInDays (type int64) as type *int64 in field value
../../go/pkg/mod/cloud.google.com/go/storage@v1.22.1/bucket.go:1592:5: cannot use rr.Condition.Age (type *int64) as type int64 in field value
```

**Comment by vnddr** [comment] 2022-09-29 08:33
Found this error too. Reproduced it with go 1.17, 1.18 and 1.19

**Comment by lahirumaramba** [comment] 2022-10-17 20:52
Hey @DaanvandeHaar , @vnddr,
We updated the `cloud.google.com/go/storage` dependency in Firebase Admin Go v4.9.0 release. Could you try the new release and see if you are still facing this issue, please? Thank you.

**Comment by lahirumaramba** [comment] 2022-10-20 16:28
I am closing this assuming the issue is now fixed with the dependency upgrade mentioned above. We can reopen later if needed. Thanks.

**Closed by lahirumaramba** 2022-10-20 16:28 UTC
Labels: api: core
